name = "tesoro-crm-website"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./dist"

# Note: Secret Store bindings for Pages are configured via Cloudflare Dashboard
# Go to: Pages Project → Settings → Functions → Bindings
# Add Secret Store binding with name "SECRETS" and ID "f232fb5497684c778c9082dab1308c64"
